- name: Gurke
  durability: 21
- name: Aprikose
  durability: 4
- name: Tomate
  durability: 10
- name: Kartoffel
  durability: 30
- name: Zwiebel
  durability: 40
- name: Karotte
  durability: 20
- name: Apfel
  durability: 14
- name: Banane
  durability: 7
- name: Orangensaft
  durability: 5
- name: Milch
  durability: 3
- name: Käse
  durability: 25
- name: Schokolade
  durability: 180
- name: Brot
  durability: 5
- name: Wasser
  durability: 365
- name: Ei
  durability: 21
- name: Hähnchenbrust
  durability: 4
- name: Tofu
  durability: 10
- name: Lachs
  durability: 3
- name: Erdbeeren
  durability: 7
- name: Salat
  durability: 7
- name: Joghurt
  durability: 14
- name: Olivenöl
  durability: 365